require("dotenv").config();
const express=require("express"),cors=require("cors"),path=require("path"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),{Pool}=require("pg");
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||"change-this-secret-in-production";
app.use(cors());app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
let pool=null;if(process.env.DATABASE_URL)pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==="false"?false:{rejectUnauthorized:false}});
const memory={users:[{id:1,name:"Admin",email:"admin@flynext.pk",passwordHash:bcrypt.hashSync(process.env.ADMIN_PASSWORD||"Admin@123",10),role:"admin"}],leads:[{id:1,customer_name:"Demo Customer",channel:"WhatsApp",category:"Fresh Ticket",route:"PEW-JED",message:"Need fare and availability for tomorrow",status:"New",assigned_to:"Admin",created_at:new Date().toISOString()},{id:2,customer_name:"Travel Agent",channel:"Facebook",category:"Reissue",route:"DOH-PEW",message:"Please check date change charges",status:"Contacted",assigned_to:"Admin",created_at:new Date().toISOString()}],messages:[]};
async function db(q,p=[]){if(!pool)return null;return(await pool.query(q,p)).rows}
async function initDb(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'agent',created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS leads(id SERIAL PRIMARY KEY,customer_name TEXT NOT NULL,channel TEXT NOT NULL,category TEXT NOT NULL,route TEXT DEFAULT '',message TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'New',assigned_to TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS messages(id SERIAL PRIMARY KEY,lead_id INTEGER REFERENCES leads(id) ON DELETE CASCADE,direction TEXT NOT NULL,channel TEXT NOT NULL,body TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());`);const c=await pool.query("SELECT COUNT(*)::int count FROM users");if(c.rows[0].count===0){const h=await bcrypt.hash(process.env.ADMIN_PASSWORD||"Admin@123",10);await pool.query("INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4)",["Admin",process.env.ADMIN_EMAIL||"admin@flynext.pk",h,"admin"]);}}
function auth(req,res,next){const t=(req.headers.authorization||"").replace("Bearer ","");try{req.user=jwt.verify(t,JWT_SECRET);next()}catch{res.status(401).json({error:"Unauthorized"})}}
const categories=["Fresh Ticket","Reissue","Date Change","Sector Change","Fare","Availability","Refund"],statuses=["New","Contacted","Quote","Won","Lost"],channels=["WhatsApp","Facebook","Instagram","TikTok","YouTube","Manual"];
app.get("/api/health",(req,res)=>res.json({ok:true,app:"Fly Next Social Hub",database:!!pool}));
app.post("/api/auth/login",async(req,res)=>{const{email,password}=req.body||{};let u=pool?(await db("SELECT id,name,email,password_hash,role FROM users WHERE email=$1",[email]))[0]:memory.users.find(x=>x.email===email);if(!u||!(await bcrypt.compare(password||"",u.password_hash||u.passwordHash)))return res.status(401).json({error:"Invalid email or password"});const safe={id:u.id,name:u.name,email:u.email,role:u.role};res.json({token:jwt.sign(safe,JWT_SECRET,{expiresIn:"12h"}),user:safe})});
app.get("/api/dashboard",auth,async(req,res)=>{const l=pool?await db("SELECT * FROM leads ORDER BY created_at DESC"):memory.leads;res.json({stats:Object.fromEntries(statuses.map(s=>[s,l.filter(x=>x.status===s).length])),total:l.length,recent:l.slice(0,8)})});
app.get("/api/leads",auth,async(req,res)=>{const{status,category,channel,q}=req.query;let l=pool?await db("SELECT * FROM leads ORDER BY created_at DESC"):memory.leads;l=l.filter(x=>(!status||x.status===status)&&(!category||x.category===category)&&(!channel||x.channel===channel)&&(!q||JSON.stringify(x).toLowerCase().includes(String(q).toLowerCase())));res.json(l)});
app.post("/api/leads",auth,async(req,res)=>{const b=req.body||{},x={customer_name:b.customer_name||"Unknown",channel:channels.includes(b.channel)?b.channel:"Manual",category:categories.includes(b.category)?b.category:"Fresh Ticket",route:b.route||"",message:b.message||"",status:"New",assigned_to:req.user.name};if(pool){const r=await db("INSERT INTO leads(customer_name,channel,category,route,message,status,assigned_to) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[x.customer_name,x.channel,x.category,x.route,x.message,x.status,x.assigned_to]);return res.status(201).json(r[0])}x.id=Math.max(0,...memory.leads.map(a=>a.id))+1;x.created_at=new Date().toISOString();memory.leads.unshift(x);res.status(201).json(x)});
app.patch("/api/leads/:id",auth,async(req,res)=>{const id=Number(req.params.id),{status,category,assigned_to}=req.body||{};if(pool){const r=await db("UPDATE leads SET status=COALESCE($1,status),category=COALESCE($2,category),assigned_to=COALESCE($3,assigned_to),updated_at=NOW() WHERE id=$4 RETURNING *",[status,category,assigned_to,id]);return r[0]?res.json(r[0]):res.status(404).json({error:"Lead not found"})}const x=memory.leads.find(a=>a.id===id);if(!x)return res.status(404).json({error:"Lead not found"});if(statuses.includes(status))x.status=status;if(categories.includes(category))x.category=category;if(assigned_to)x.assigned_to=assigned_to;res.json(x)});
app.get("/api/leads/:id/messages",auth,async(req,res)=>{const id=Number(req.params.id);res.json(pool?await db("SELECT * FROM messages WHERE lead_id=$1 ORDER BY created_at",[id]):memory.messages.filter(x=>x.lead_id===id))});
app.post("/api/leads/:id/messages",auth,async(req,res)=>{const id=Number(req.params.id),body=String(req.body?.body||"").trim();if(!body)return res.status(400).json({error:"Message is required"});if(pool){const r=await db("INSERT INTO messages(lead_id,direction,channel,body) SELECT $1,'outbound',channel,$2 FROM leads WHERE id=$1 RETURNING *",[id,body]);if(!r[0])return res.status(404).json({error:"Lead not found"});await db("UPDATE leads SET status='Contacted',updated_at=NOW() WHERE id=$1",[id]);return res.status(201).json(r[0])}const l=memory.leads.find(x=>x.id===id);if(!l)return res.status(404).json({error:"Lead not found"});const m={id:memory.messages.length+1,lead_id:id,direction:"outbound",channel:l.channel,body,created_at:new Date().toISOString()};memory.messages.push(m);l.status="Contacted";res.status(201).json(m)});
app.get("/api/meta/status",auth,(req,res)=>res.json({whatsapp:!!process.env.WHATSAPP_ACCESS_TOKEN,facebook:!!process.env.META_ACCESS_TOKEN,instagram:!!process.env.META_ACCESS_TOKEN,tiktok:!!process.env.TIKTOK_ACCESS_TOKEN,youtube:!!process.env.YOUTUBE_ACCESS_TOKEN}));
app.post("/webhooks/meta",(req,res)=>res.status(200).send("EVENT_RECEIVED"));app.get("/webhooks/meta",(req,res)=>{const m=req.query["hub.mode"],t=req.query["hub.verify_token"],c=req.query["hub.challenge"];if(m==="subscribe"&&t&&t===process.env.META_VERIFY_TOKEN)return res.status(200).send(c);res.sendStatus(403)});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));initDb().then(()=>app.listen(PORT,()=>console.log("Fly Next Social Hub running on port "+PORT))).catch(e=>{console.error(e);process.exit(1)});
